### ISSUE TITLE
Ability to restrict activations per stage / container?

### ISSUE THREAD

**Issue by sirusdv** [electronicarts/orbit#6]
Congrats on releasing! 

I would like to be able to restrict activations of certain actors on a per stage / container basis without having to rely on multiple processes.  

Eg, consider the scenario of a memory-usage heavy actor on a machine that in theory could only support 10 of. 

I thought about doing this by creating multiple stages and restricting the sizes of the execution pools. However, actor auto discovery seems to get in the way here. 

In the AsymmetricalStagesTest something similar is achieved through reflection by setting a custom Execution on the private execution field but that seems hack-y.

I can see that I could set the orbit.actors.autoDiscovery property but there is still no access the Execution instance to call the addActorClasses method.

Thoughts?

**Comment by JoeHegarty** [comment]
Actor Locality and Placement isn't something that the framework lets you control right now (beyond what actors are available in the classpath as you discovered in the asymmetrical test).
We do plan on adding options for more strictly defining placement but I don't have a clear timeframe on that.
I'm going to let @DanielSperry chime in, as he is more familiar with the the ins-and-outs of the Execution system, so he may have some ideas about how to achieve what you need.

**Comment by sirusdv** [comment]
I'd be happy to spend time implementing something like this if there were design guidelines laid out.

**Comment by DanielSperry** [comment]
Hi sirusdv,

As @JoeHegarty mentioned, we're planing on adding support for hooks to the activation algorithm on a later release.
But I see that you're trying to do it yourself with the current classes.

I guess you want the same type of actor, let's say `IWorldSimulator`, distributed across different nodes, and want guarantees about how many and where.
Asymmetrical nodes are nodes that never activate certain types of actor. So probably not what you are looking for.

The node selection happens in `Hosting.selectNode()`.
We will probably enable adding hooks to that process.
There are tons of potential pitfalls since the hook code might want to send remote messages during the selection process, causing deadlocks or infinity recursion.
If you want to experiment with that we would be more than willing to accept pull requests.
p.s. `ILifecyleProvider` might be used to monitor the active actors in a certain node.

Another option is handling this yourself implementing the memory/cpu heavy processing in `IActorObservers` local to the server nodes. 
I don't recommend that because it shifts the burden of managing the lifecycle/persistence/addressing of those objects to your application.

**Comment by JoeHegarty** [comment]
Closing this one for now. Feel free to continue using it open another issue :smile:
