### ISSUE TITLE
Registered timer with 0 period value doesn't work properly

### ISSUE THREAD

**Issue by fixedorgo** [electronicarts/orbit#97]
As an example, please try something like:
```java
registerTimer(() -> tick(), 1000, 0, TimeUnit.MILLISECONDS);
```
Unfortunately, there will be no Exception (good old java Threads). A main discrepancy here is that `Runtime` interface doc said:
```
...
* @param period       the period of subsequent ticks (if ZERO then will only tick once)
...
```
But we are unable to register `Timer` with 0 period value due to this precondition check:
```java
if (period <= 0)
            throw new IllegalArgumentException("Non-positive period.");
``` 
We have to use `Timer.schedule(TimerTask task, long delay);` method instead. I think, scheduling some task just once is very useful. Please, could you provide this ability? I would say, that overloaded `registerTimer()` will be the best.

**Comment by JoeHegarty** [comment]
I agree that this behavior is desirable. We'll get this added shortly.

**Comment by fixedorgo** [comment]
Please, could you add some precondition check or at least corresponding comment for the current method? Because the temptation of setting `0` value is great, but as a result nothing happens and without any exception.

**Comment by JoeHegarty** [comment]
I've made it so the behavior of the timer now matches the documentation. Your example will now work as you expect.

Exceptions from the timer system are correctly thrown, but you'll need to catch them on your call to registerTimer otherwise it will just cause the wrapping task to fail exceptionally (which may or may not get logged depending on who is waiting on that task).

Hopefully that resolves your issue. Thanks for reporting it, let me know if you have any further problems.

**Comment by fixedorgo** [comment]
Thanks a lot, Joe! I will.
